apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello world
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  test:
    environment: staging
    steps:
      - uses: test
        kind: deploy
      - uses: test
        kind: deploy
    outputs:
      test: test
